/**
 * main.m
 * Generated by kimi
 */

#import <UIKit/UIKit.h>
#import "TAAppDelegate.h"
#import "TAAppDebugLog.h"

int main(int argc, char *argv[]) {
    @autoreleasepool {
        TAInstallCrashHandlers();
        TASetDebugStage(@"main_start");
        return UIApplicationMain(argc, argv, nil, NSStringFromClass([TAAppDelegate class]));
    }
}
