/**
 * TAAppDelegate.mm
 * Generated by kimi for module: app_delegate
 */

#import "TAAppDelegate.h"
#import "TACoinbaseAPI.h"
#import "TAPortfolio.h"
#import "TAChartView.h"
#import "TADashboardViewController.h"
#import "TAPortfolioViewController.h"
#import "TAWatchlistViewController.h"
#import "TAJournalViewController.h"
#import "TASettingsViewController.h"
#import "TAAppDebugLog.h"

@implementation TAAppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    TASetDebugStage(@"app_delegate_start");
    [self seedDefaultsIfNeeded];
    TASetDebugStage(@"seed_defaults_done");
    self.window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    TASetDebugStage(@"window_created");
    
    TADashboardViewController *dashboard = [[TADashboardViewController alloc] init];
    TAPortfolioViewController *portfolio = [[TAPortfolioViewController alloc] init];
    TAWatchlistViewController *watchlist = [[TAWatchlistViewController alloc] init];
    TASettingsViewController *settings = [[TASettingsViewController alloc] init];

    UINavigationController *dashboardNav = [[UINavigationController alloc] initWithRootViewController:dashboard];
    UINavigationController *portfolioNav = [[UINavigationController alloc] initWithRootViewController:portfolio];
    UINavigationController *watchlistNav = [[UINavigationController alloc] initWithRootViewController:watchlist];
    UINavigationController *settingsNav = [[UINavigationController alloc] initWithRootViewController:settings];

    NSArray<UINavigationController *> *navs = @[dashboardNav, portfolioNav, watchlistNav, settingsNav];
    for (UINavigationController *nav in navs) {
        nav.navigationBar.barStyle = UIBarStyleBlack;
        nav.navigationBar.tintColor = [UIColor colorWithRed:0.2 green:0.9 blue:0.7 alpha:1.0];
    }

    UIImage *tradeIcon = [UIImage systemImageNamed:@"chart.bar"];
    UIImage *portfolioIcon = [UIImage systemImageNamed:@"briefcase"];
    UIImage *watchlistIcon = [UIImage systemImageNamed:@"star"];
    UIImage *settingsIcon = [UIImage systemImageNamed:@"gear"];

    dashboardNav.tabBarItem = [[UITabBarItem alloc] initWithTitle:@"Trade" image:tradeIcon tag:0];
    portfolioNav.tabBarItem = [[UITabBarItem alloc] initWithTitle:@"Portfolio" image:portfolioIcon tag:1];
    watchlistNav.tabBarItem = [[UITabBarItem alloc] initWithTitle:@"Watchlist" image:watchlistIcon tag:2];
    settingsNav.tabBarItem = [[UITabBarItem alloc] initWithTitle:@"Settings" image:settingsIcon tag:3];

    UITabBarController *tabBar = [[UITabBarController alloc] init];
    tabBar.viewControllers = navs;
    tabBar.tabBar.barTintColor = [UIColor blackColor];
    tabBar.tabBar.tintColor = [UIColor colorWithRed:0.2 green:0.9 blue:0.7 alpha:1.0];
    tabBar.tabBar.unselectedItemTintColor = [UIColor colorWithWhite:0.6 alpha:1.0];

    self.window.rootViewController = tabBar;
    TASetDebugStage(@"root_set");
    [self.window makeKeyAndVisible];
    TASetDebugStage(@"window_visible");
    
    return YES;
}

- (void)seedDefaultsIfNeeded {
    NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
    NSString *apiKey = [defaults stringForKey:@"coinbase_api_key"];
    NSString *privateKey = [defaults stringForKey:@"coinbase_private_key"];
    BOOL needsSeed = (apiKey.length == 0 || privateKey.length == 0);
    if (!needsSeed) {
        if (![apiKey containsString:@"/apiKeys/"] || privateKey.length < 40) {
            needsSeed = YES;
        }
    }

    // Treat short base64 keys (no PEM header, too short to be DER) as invalid
    if (!needsSeed && privateKey.length > 0 && ![privateKey containsString:@"BEGIN"]) {
        if (privateKey.length < 120) {
            needsSeed = YES;
        }
    }

    if (needsSeed) {
        NSString *path = [[NSBundle mainBundle] pathForResource:@"iostest2" ofType:@"json"];
        if (path) {
            NSData *data = [NSData dataWithContentsOfFile:path];
            if (data) {
                NSError *error = nil;
                NSDictionary *json = [NSJSONSerialization JSONObjectWithData:data options:0 error:&error];
                if ([json isKindOfClass:[NSDictionary class]] && !error) {
                    NSString *name = json[@"name"];
                    NSString *key = json[@"privateKey"];
                    if (name.length > 0 && key.length > 0) {
                        [defaults setObject:name forKey:@"coinbase_api_key"];
                        [defaults setObject:key forKey:@"coinbase_private_key"];
                    }
                }
            }
        }
    }

    NSString *edApiKey = [defaults stringForKey:@"coinbase_ed25519_api_key"];
    NSString *edPrivateKey = [defaults stringForKey:@"coinbase_ed25519_private_key"];
    if (edApiKey.length == 0 || edPrivateKey.length == 0) {
        NSString *edPath = [[NSBundle mainBundle] pathForResource:@"linux2" ofType:@"json"];
        if (edPath) {
            NSData *data = [NSData dataWithContentsOfFile:edPath];
            if (data) {
                NSError *error = nil;
                NSDictionary *json = [NSJSONSerialization JSONObjectWithData:data options:0 error:&error];
                if ([json isKindOfClass:[NSDictionary class]] && !error) {
                    NSString *kid = json[@"id"];
                    NSString *key = json[@"privateKey"];
                    if (kid.length > 0 && key.length > 0) {
                        [defaults setObject:kid forKey:@"coinbase_ed25519_api_key"];
                        [defaults setObject:key forKey:@"coinbase_ed25519_private_key"];
                    }
                }
            }
        }
    }

    if (![defaults stringForKey:@"openrouter_model"]) {
        [defaults setObject:@"openai/gpt-4o-mini" forKey:@"openrouter_model"];
    }
    if ([defaults objectForKey:@"coinbase_ed25519_use_full_name"] == nil) {
        [defaults setBool:NO forKey:@"coinbase_ed25519_use_full_name"];
    }
    NSString *jwtMode = [defaults stringForKey:@"coinbase_jwt_uri_mode"];
    if (!jwtMode || ![jwtMode isEqualToString:@"https"]) {
        [defaults setObject:@"https" forKey:@"coinbase_jwt_uri_mode"];
    }
    if ([defaults objectForKey:@"coinbase_ecdsa_use_full_name"] == nil) {
        [defaults setBool:NO forKey:@"coinbase_ecdsa_use_full_name"];
    }
    [defaults synchronize];
}

- (void)applicationDidBecomeActive:(UIApplication *)application {
    TASetDebugStage(@"app_did_become_active");
}

- (void)applicationWillResignActive:(UIApplication *)application {
    TASetDebugStage(@"app_will_resign_active");
}

- (void)applicationDidEnterBackground:(UIApplication *)application {
    TASetDebugStage(@"app_did_enter_background");
}

- (void)applicationWillEnterForeground:(UIApplication *)application {
    TASetDebugStage(@"app_will_enter_foreground");
}

- (void)applicationWillTerminate:(UIApplication *)application {
    TASetDebugStage(@"app_will_terminate");
    TAAppendDebugLog(@"app_will_terminate");
}

@end
