/**
 * TAAppDelegate.h
 * Generated by kimi for module: app_delegate
 * Timestamp: 2026-01-30T22:31:04.676522
 */

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

@interface TAAppDelegate : UIResponder <UIApplicationDelegate>
@property (strong, nonatomic) UIWindow *window;
@end

NS_ASSUME_NONNULL_END
