/**
 * TAChartView.h
 * Generated by codex for module: chart_view
 * Timestamp: 2026-01-30T22:31:04.676236
 */

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

@interface TAChartView : UIView
@property (nonatomic, copy) NSString *symbol;
@property (nonatomic, strong) NSArray *priceData;
- (void)updateWithCandles:(NSArray *)candles;
- (void)reloadData;
- (void)setTimeframe:(NSString *)timeframe;
@end

NS_ASSUME_NONNULL_END
