/**
 * TAPortfolio.mm
 * Generated by qwen for module: portfolio
 */

#import "TAPortfolio.h"
#import "TACoinbaseAPI.h"
#import "TAPortfolio.h"
#import "TAChartView.h"

@implementation TAHolding

- (NSDecimalNumber *)value {
    return [self.quantity decimalNumberByMultiplyingBy:self.currentPrice];
}

- (NSDecimalNumber *)pnl {
    NSDecimalNumber *cost = [self.quantity decimalNumberByMultiplyingBy:self.avgPrice];
    return [[self value] decimalNumberBySubtracting:cost];
}

@end

@interface TAPortfolio ()
@property (nonatomic, strong) NSMutableDictionary<NSString *, TAHolding *> *holdings;
@property (nonatomic, strong) NSMutableArray *tradeHistory;
@end

@implementation TAPortfolio

+ (instancetype)sharedInstance {
    static TAPortfolio *instance = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{ instance = [[self alloc] init]; });
    return instance;
}

- (instancetype)init {
    self = [super init];
    if (self) {
        _holdings = [NSMutableDictionary dictionary];
        _tradeHistory = [NSMutableArray array];
    }
    return self;
}

- (void)updateHolding:(NSString *)symbol quantity:(NSDecimalNumber *)quantity price:(NSDecimalNumber *)price {
    TAHolding *holding = self.holdings[symbol];
    if (!holding) {
        holding = [[TAHolding alloc] init];
        holding.symbol = symbol;
        holding.avgPrice = price;
        self.holdings[symbol] = holding;
    }
    holding.quantity = quantity;
    holding.currentPrice = price;
}

- (NSArray<TAHolding *> *)getHoldings {
    return [self.holdings allValues];
}

- (NSDecimalNumber *)getTotalValue {
    NSDecimalNumber *total = [NSDecimalNumber zero];
    for (TAHolding *holding in self.holdings.allValues) {
        total = [total decimalNumberByAdding:[holding value]];
    }
    return total;
}

- (NSDecimalNumber *)getTotalPNL {
    NSDecimalNumber *pnl = [NSDecimalNumber zero];
    for (TAHolding *holding in self.holdings.allValues) {
        pnl = [pnl decimalNumberByAdding:[holding pnl]];
    }
    return pnl;
}

- (void)recordTrade:(NSString *)symbol side:(NSString *)side quantity:(NSDecimalNumber *)quantity price:(NSDecimalNumber *)price {
    NSDictionary *trade = @{
        @"symbol": symbol,
        @"side": side,
        @"quantity": quantity,
        @"price": price,
        @"timestamp": [NSDate date]
    };
    [self.tradeHistory addObject:trade];
}

@end
