/**
 * TAPortfolio.h
 * Generated by qwen for module: portfolio
 * Timestamp: 2026-01-30T22:31:04.676025
 */

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

@interface TAHolding : NSObject
@property (nonatomic, copy) NSString *symbol;
@property (nonatomic, strong) NSDecimalNumber *quantity;
@property (nonatomic, strong) NSDecimalNumber *avgPrice;
@property (nonatomic, strong) NSDecimalNumber *currentPrice;
- (NSDecimalNumber *)value;
- (NSDecimalNumber *)pnl;
@end

@interface TAPortfolio : NSObject
+ (instancetype)sharedInstance;
- (void)updateHolding:(NSString *)symbol quantity:(NSDecimalNumber *)quantity price:(NSDecimalNumber *)price;
- (NSArray<TAHolding *> *)getHoldings;
- (NSDecimalNumber *)getTotalValue;
- (NSDecimalNumber *)getTotalPNL;
- (void)recordTrade:(NSString *)symbol side:(NSString *)side quantity:(NSDecimalNumber *)quantity price:(NSDecimalNumber *)price;
@end

NS_ASSUME_NONNULL_END
